giravolt:
  active: true
  name: Giravolt
  mqtt_topic: Dades-Fotovoltaiques-consum-giravolt32

residencia:
  active: true
  name: Residència
  mqtt_topic: Generacio-Residencia

sala-polivalent:
  active: true
  name: Sala Polivalent
  mqtt_topic: Generacio-SalaPolivalent